Parameters:
  VpcCidrparamBlock:
    Description: Parameter Block for VPC CIDR
    Type: String
    Default: 10.24.0.0/16

  PublicSubnetCidrBlock:
    Description: Parameter for Public Subnet Cidr
    Type: String
    Default: 10.24.0.0/24
  PrivateSubnetCidrBlock:
    Description: Parameter for Private Subnet Cidr
    Type: String
    Default: 10.24.1.0/24

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0fff1b9a61dec8a5f
    us-west-1:
      AMI: ami-0cf4e1fcfd8494d5b


Resources:
  Lab1FridayHITTVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidrparamBlock
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
       - Key: Name
         Value: Lab1-VPC


  Lab1FridayHITTInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: Lab1-InternetGateway

  lab1FridayHITTAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref Lab1FridayHITTVPC
      InternetGatewayId: !Ref Lab1FridayHITTInternetGateway
  
  Lab1FridayHITTPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Lab1FridayHITTVPC
      MapPublicIpOnLaunch: 'true'                   # To automatically Launch IP address
      CidrBlock: !Ref PublicSubnetCidrBlock
      AvailabilityZone: !Select [1, !GetAZs '']
      Tags:
      - Key: Name
        Value: Lab1-PublicSubnet

  Lab1FridayHITTPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Lab1FridayHITTVPC
      Tags:
      - Key: Name
        Value: Lab1-PublicRouteTable

  Lab1FridayHITTPublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Lab1FridayHITTPublicSubnet
      RouteTableId: !Ref Lab1FridayHITTPublicRouteTable

  Lab1FridayHITTPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: Lab1FridayHITTInternetGateway                                  #To be found only after Internet Gateway successfully attached to the VPC
    Properties:
       RouteTableId: !Ref Lab1FridayHITTPublicRouteTable
       DestinationCidrBlock: 0.0.0.0/0                                 #Specifies the Destination match
       GatewayId: !Ref Lab1FridayHITTInternetGateway

### Private Subnet Routing ###
  Lab1FridayHITTPrivateSubnet:                                              ### Private Subnet ###
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Lab1FridayHITTVPC
      CidrBlock: !Ref PrivateSubnetCidrBlock
      AvailabilityZone: !Select [1, !GetAZs '']
      Tags:
      - Key: Name
        Value: Lab1-PrivateSubnet

  Lab1FridayHITTPrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Lab1FridayHITTVPC
      Tags:
      - Key: Name
        Value: Lab1-PrivateRouteTable


  Lab1FridayHITTPrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Lab1FridayHITTPrivateSubnet
      RouteTableId: !Ref Lab1FridayHITTPrivateRouteTable

  # Security Group for the Public EC2 instance in public subnet
  Lab1FridayHITTPublicEC2InstanceSGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows SSH access to the public EC2 instance
      VpcId: !Ref Lab1FridayHITTVPC
      SecurityGroupIngress:
        - IpProtocol: tcp                      # To Allow SSH
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp                      # To allow HTTP
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp                      # To allow HTTPS
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: Lab1-PublicEC2SGrp

  # Security Group for the Private EC2 instance in private subnet
  Lab1FridayHITTPrivateEC2InstanceSGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access from the Public instancecat 
      VpcId: !Ref Lab1FridayHITTVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref Lab1FridayHITTJumpBoxSGrp
      Tags:
        - Key: Name
          Value: Lab1-PrivateEC2SGrp

  # Implementing Public EC2 Instance
  Lab1FridayHITTPublicEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: FridayHITTP_project
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]  # Select AMI ID depending on the region
      SubnetId: !Ref Lab1FridayHITTPublicSubnet
      SecurityGroupIds:
        - !Ref Lab1FridayHITTPublicEC2InstanceSGrp
      Tags:
        - Key: Name
          Value: Lab1-PublicEC2Instance

  # Implementing Private EC2 Instance
  Lab1FridayHITTPrivateEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: FridayHITTP_project
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]  # Select AMI ID depending on the region
      SubnetId: !Ref Lab1FridayHITTPrivateSubnet
      SecurityGroupIds:
        - !Ref Lab1FridayHITTPrivateEC2InstanceSGrp
      Tags:
        - Key: Name
          Value: Lab1-PrivateEc2Instance

  # Security Group for Jump Host
  Lab1FridayHITTJumpBoxSGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows to SSH to the Jump Host
      VpcId: !Ref Lab1FridayHITTVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  # Allow SSH from Public Subnet ( Recommended to use VPN range in organization )
      Tags:
        - Key: Name
          Value: Lab1-JumpBoxEC2SGrp
  # Jump Host in Public Subnet
  Lab1FridayHITTJumpBox:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: FridayHITTP_project
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]  # Select AMI ID depending on the region
      SubnetId: !Ref Lab1FridayHITTPublicSubnet
      SecurityGroupIds:
        - !Ref Lab1FridayHITTJumpBoxSGrp
      Tags:
        - Key: Name
          Value: Lab1-JumpBox

Outputs:
  VpcId:
    Description: VPC ID of FridayHITT company
    Value: !Ref Lab1FridayHITTVPC
  InternetGateway:
    Value: !Ref Lab1FridayHITTInternetGateway
  PublicSubnet:
    Value: !Ref Lab1FridayHITTPublicSubnet
  PrivateSubnet:
    Value: !Ref Lab1FridayHITTPrivateSubnet
  PublicInstancePublicIP:
    Value: !GetAtt Lab1FridayHITTPublicEC2Instance.PublicIp
  JumpBoxInstancePublicIP:
    Value: !GetAtt Lab1FridayHITTJumpBox.PublicIp
